discuss/web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack
    
    get "/", PageController, :index
    get "/home", PageController, :index
    get "/get-started", CodeController, :index
    
    resources "/topics", TopicsController
  end
  
  scope "/auth", Discuss do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end

discuss/web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

discuss/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = "<%= Phoenix.Token.sign(Discuss.Endpoint, "key", @conn.assigns.user.id) %>"
      <% end %>
    </script>
  </head>

  <body>
    <header class="header">
      <nav role="navigation" class="grey lighten-3">
        <div class="nav-wrapper">
          <span class="logo brand-logo"></span>
          <ul class="right hide-on-med-and-down">
            <li>
              <%= link to: page_path(@conn, :index), class: "btn" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link to: topics_path(@conn, :index), class: "btn" do %>
                <i class="fas fa-th-list"></i> Topics
              <% end %>
            </li>
            <li>
              <%= link to: code_path(@conn, :index), class: "btn" do %>
                <i class="fab fa-free-code-camp"></i> Get Started
              <% end %>
            </li>
            <li>
              <%= if @conn.assigns[:user] do %>
                <a class='dropdown-button btn' href='#' data-activates='sing_out_dropdown'>
                  <%= @conn.assigns[:user].name %>
                </a>

                <ul id='sing_out_dropdown' class='dropdown-content'>
                    <%= link to: auth_path(@conn, :signout), class: "btn" do %>
                    <i class="fas fa-sign-out-alt"></i> Logout
                  <% end %>
                </ul>
                
              <% else %>
                <a class='dropdown-button btn' href='#' data-activates='sing_in_dropdown'>
                  <i class="fas fa-sign-in-alt"></i> Sign In
                </a>

                <ul id='sing_in_dropdown' class='dropdown-content'>
                  <li>
                    <%= link to: auth_path(@conn, :request, "github"), class: "btn green" do %>
                       <i class="fab fa-github-square"></i> Github
                    <% end %>
                  </li>
                  <li>
                    <%= link to: auth_path(@conn, :request, "facebook"), class: "btn yellow" do %>
                      <i class="fas fa-facebook-square"></i> Facebook
                    <% end %>
                  </li>
                </ul>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </header>

      
      <div class="container">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>
    
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>